version: '3.8'
services:
  fiber-db:
    image: postgres:latest
    container_name: fiber-db
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - Heepoke

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fiber-api
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - fiber-db
    networks:
      - Heepoke

networks:
  Heepoke:
    driver: bridge